server:
  port: 3232


management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
zuul:
  host:
    socket-timeout-millis: 2000000
  ribbon:
     eager-load:
      enabled: true
 
  routes:
    recomend-service:
       path: /recomend-service/**
       url: http://localhost:7070/client  
    api:     
      path: /api/**
      service-id: resource
      sensitiveHeaders:
      strip-prefix: false
      url: http://localhost:5050/
    